DAO layer is created, FamilyDto is added to Human class, getAllFamili…
ayten-github/happy_family_project pull request #15
Opened 2024-10-13 17:58 UTC by 2kfarid3

…es and createNewFamily method is written,HappyFamilyApp class is written temporary

2024-10-13 18:46 UTC, sabuhihuseynov commented on src/main/java/az/edu/strangers/Human.java
> +    private FamilyDto familyDto;
this model should not be here

2024-10-13 18:46 UTC, sabuhihuseynov commented on src/main/java/az/edu/strangers/controller/FamilyController.java
> +    FamilyService familyService;
make private

2024-10-13 18:48 UTC, sabuhihuseynov commented on src/main/java/az/edu/strangers/dao/FamilyDao.java
> +public interface FamilyDao<T> {
I think no need Generic here, this dao for the `Family` class

2024-10-13 18:49 UTC, sabuhihuseynov commented on src/main/java/az/edu/strangers/service/FamilyServiceImpl.java
> +        Woman mother = new Woman(women.getName(), women.getSurname(), women.getYear());
why recreate sended objects?

2024-10-13 18:49 UTC, sabuhihuseynov requested changes
pls look

2024-10-14 14:18 UTC, ayten-github commented
Because of some changes

2024-10-14 14:18 UTC, closed without merging

2024-10-14 14:19 UTC, ayten-github commented
.